//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDemoYP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovar()
        {
            this.Sostav = new HashSet<Sostav>();
        }
    
        public int Title { get; set; }
        public string Edinica { get; set; }
        public Nullable<double> Price { get; set; }
        public int Supplier { get; set; }
        public int Manufacturer { get; set; }
        public int Category { get; set; }
        public Nullable<double> Sale { get; set; }
        public Nullable<int> CountOnSklad { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
        public int ID_Tovar { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual Manufacturer Manufacturer1 { get; set; }
        public virtual Postavchick Postavchick { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sostav> Sostav { get; set; }
        public virtual Title Title1 { get; set; }

        public double OriginalPriceValue
        {
            get { return Price ?? 0; }
        }

        public bool HasDiscount
        {

            get
            {
                return Sale != null && Sale > 0.001;
            }
        }

        public double DiscountedPriceValue
        {
            get
            {
                if (Sale != null && Sale > 0.001) 
                    return Math.Round((Price ?? 0) * (1 - Sale.Value / 100), 2);

                return 0;
            }
        }
    }
}
