//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDemoYP
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Roles
    {
        public int ID_UR { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<int> ID_Role { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
