//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDemoYP
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Order
    {
        public int ID_UO { get; set; }
        public Nullable<int> ID_Order { get; set; }
        public Nullable<int> ID_User { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Users Users { get; set; }
    }
}
